import ExpandableText from './components/ExpandableText';

const App = () => {
  return (
    <ExpandableText text="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus quis quidem velit est fugit vel, consequatur dolorem illo officia sunt quam quasi, error, fuga incidunt porro. At quidem deserunt accusantium officiis illum placeat vel debitis, cumque veniam accusamus pariatur, eum tempora quis natus nihil, similique eveniet. Repellat enim animi ex, laboriosam, consequatur amet nesciunt impedit quae deserunt voluptate dicta distinctio ipsum cumque, voluptatem quidem illo minus? Excepturi voluptatum vel architecto culpa id ducimus omnis ab, placeat quibusdam mollitia at esse corporis dignissimos nobis. Recusandae labore accusamus nobis veritatis repudiandae. Culpa rem labore quaerat, natus necessitatibus fugiat eveniet minima suscipit ratione debitis enim quas maiores soluta, inventore laboriosam, eum porro quam mollitia. Animi porro quisquam quaerat suscipit quasi vitae voluptas praesentium in necessitatibus pariatur possimus omnis reiciendis nisi facilis, recusandae, id laborum ea, amet placeat magnam quas. Quam modi doloribus necessitatibus saepe consequatur? Minus cupiditate dolor praesentium veniam optio inventore illum architecto ea, maxime unde necessitatibus, corporis sint quis voluptatum atque aliquid, commodi iure repudiandae adipisci quos. Repudiandae vitae, cumque ducimus maiores inventore accusamus facilis error quisquam placeat non excepturi soluta quaerat culpa at sequi. Dolorem voluptatibus animi quia praesentium quas obcaecati id incidunt illo natus neque et, consequatur sed repellendus consequuntur ratione officiis, voluptatum dolores optio. Facilis similique reprehenderit maxime voluptatibus, nisi molestiae hic porro ad asperiores corporis! Laborum blanditiis veniam necessitatibus ad voluptatibus itaque harum nihil vero iste sed suscipit, vel consequatur odit dicta ex. Minus, nam. Repellendus, soluta! Provident aspernatur aliquid labore nulla quisquam sequi libero enim praesentium voluptatum eveniet itaque perferendis impedit quia saepe iste vero iusto, beatae nostrum voluptate rem odio est! Earum possimus itaque aliquid ullam illo. Ullam inventore repellat, similique maxime esse aliquam impedit praesentium earum repudiandae possimus, repellendus, laboriosam beatae fuga harum corporis obcaecati tempore nisi. Officiis vitae nulla minus beatae! Maxime." />
  );
};

export default App;
